---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
    spec:
      containers:
      - name: application
        command: ["node","/app/app.js"]
        image: {{ tuple "backend" . | include "werf_image" }}
        workingDir: /app
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: "DEBUG"
          value: "{{ pluck .Values.global.env .Values.app.debugByEnv | first | default .Values.app.debugByEnv._default }}"
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 3
      - name: noisy-sidecar
        image: ubuntu:18.04
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 1; echo Some log; done;" ]
